### PR TITLE
Fix the uninitialized g_hWinHttpModule global variable to avoid empty error messages

### LINKED ISSUE #224: The g_hWinHttpModule global variable is never assigned to
The `g_hWinHttpModule` global variable (declared in forwardinghandler.h) is never assigned to.

It is only ever used as an argument to `FormatMessage` function, which will fail to look up error message when `lpSource` parameter is not a valid module handle.

### PR DESCRIPTION
**Pull request by 0xfeeddeadbeef**
Fixes #224

Feel free to discard this pull request, because I am not quite confident in my C++ skills — this might be completely wrong way to fix the issue. Also, I was not able to test it 😞 

- Assign module handle of winhttp.dll to `g_hWinHttpModule` in `RegisterModule` function.
 
- Lots of error codes between `WINHTTP_ERROR_BASE` and `WINHTTP_ERROR_LAST` do not
have corresponding entries in winhttp.dll message resource table; use defensive
coding to fall back to the default error message (`IDS_SERVER_ERROR`) when necessary.

For example, winhttp.dll on Windows Server 2012 R2 does not have message resource for `ERROR_WINHTTP_INVALID_HEADER`.

Running this code snippet will demonstrate that most valid error codes do not have corresponding message resources:

```c++
DWORD dwError = ERROR_SUCCESS;
HMODULE g_hWinHttpModule = GetModuleHandle(TEXT("winhttp.dll"));
TCHAR msgBuffer[0x10000 / sizeof(TCHAR)];  // Max size of buffer is 64K bytes

for (DWORD winHttpError = WINHTTP_ERROR_BASE + 1;
           winHttpError <= WINHTTP_ERROR_LAST;
           winHttpError++)
{
    memset(msgBuffer, 0, sizeof msgBuffer);

    if (FormatMessage(
        FORMAT_MESSAGE_IGNORE_INSERTS | FORMAT_MESSAGE_FROM_HMODULE,
        g_hWinHttpModule,
        winHttpError,
        0,
        msgBuffer,
        ARRAYSIZE(msgBuffer),
        NULL) == 0)
    {
        dwError = GetLastError();

        // "The system cannot find message text for message number 0x%1 in the message file for %2."
        if (dwError == ERROR_MR_MID_NOT_FOUND) {
            _ftprintf_s(stderr, _T("ERROR: %lu => Message not found!\r\n"), winHttpError);
        } else {
            _ftprintf_s(stderr, _T("ERROR: %lu => %lu\r\n"), winHttpError, dwError);
        }
    }
    else
    {
        _ftprintf_s(stdout, _T("MESSAGE: %lu => %s"), winHttpError, msgBuffer);
    }
}
```

### CODE REVIEW

**Comment by ghost** [comment]
Hi, I am closing and re-opening this PR to bump the CLA service. Sorry for the inconvenience!

File: src/AspNetCore/Src/forwardinghandler.cxx [hunk 1]
```diff
@@ -1451,14 +1451,20 @@ FORWARDING_HANDLER::OnExecuteRequestHandler(
...
             FORMAT_MESSAGE_IGNORE_INSERTS | FORMAT_MESSAGE_FROM_HMODULE,
             g_hWinHttpModule,
             HRESULT_CODE(hr),
             0,
             strDescription.QueryStr(),
             strDescription.QuerySizeCCH(),
-            NULL);
+            NULL) == 0)
+            {
+                LoadString(g_hModule,
```
Comment (jkotalik) [inline src/AspNetCore/Src/forwardinghandler.cxx]: The same LoadString function is called below. I think you can simplify the logic to be have FormatMessage in the if statement.

File: src/AspNetCore/Src/dllmain.cpp [hunk 2]
```diff
@@ -191,6 +191,7 @@ HRESULT
     g_pModuleId = pModuleInfo->GetId();
     g_pszModuleName = pModuleInfo->GetName();
     g_pHttpServer = pHttpServer;
+    g_hWinHttpModule = GetModuleHandle(TEXT("winhttp.dll"));
```
Comment (jkotalik) [inline src/AspNetCore/Src/dllmain.cpp:194]: @pan-wang is this correct?

**Review by jkotalik — COMMENTED** [review]
Thanks for the contribution. Good find! Awaiting @pan-wang approval/feedback.

**Comment by pan-wang** [comment]
Nice catch. It is a tricky part. In the past we copied WinHttp.h and added a lot defines such as  ERROR_WINHTTP_INVALID_HEADER to achieve compatibility. As we cannot use this customized header file, we need revisit it and make sure nothing is missed.

**Comment by 0xfeeddeadbeef** [comment]
@jkotalik I've force-pushed changes based on your code review. As a result, your original comment is gone. Sorry.

File: src/AspNetCore/Src/forwardinghandler.cxx (hunk 1 above)
Comment (0xfeeddeadbeef) [reply src/AspNetCore/Src/forwardinghandler.cxx]: @jkotalik Done.

File: src/AspNetCore/Src/forwardinghandler.cxx [hunk 3]
```diff
@@ -1447,9 +1447,8 @@ FORWARDING_HANDLER::OnExecuteRequestHandler(
     //
     pResponse->SetStatus(502, "Bad Gateway", 3, hr);
 
-    if (hr > HRESULT_FROM_WIN32(WINHTTP_ERROR_BASE) &&
-        hr <= HRESULT_FROM_WIN32(WINHTTP_ERROR_LAST))
-    {
+    if (!(hr > HRESULT_FROM_WIN32(WINHTTP_ERROR_BASE) &&
+          hr <= HRESULT_FROM_WIN32(WINHTTP_ERROR_LAST)) ||
```
Comment (pan-wang) [inline src/AspNetCore/Src/forwardinghandler.cxx:1451]: The code logic was change here. In the old code if FormatMessage failed, we will not try LoadString. 
This change make sense to me.

**Review by pan-wang — APPROVED** [review]
